VChessProject/VChessProject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include(('chess_app.urls', 'chess_app'), namespace='chess_app')),

]

VChessProject/chess_app/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path("", views.DefaultLayoutView.as_view(), name="home_page"),
    path("base", views.base_page, name="base_page"),
    path("signup", views.SignUpView.as_view(), name="sign_up"),
    path("login", views.LogInView.as_view(), name="log-in"),
    path("logout", views.logout_view, name="log-out"),
    path("board", views.BoardView.as_view(), name="board"),
    path("play", views.PlayView.as_view(), name="play"),
    path("live/<int:game_id>", views.OnlineGameView.as_view(), name="online_game"),
]

ajax_patterns = [
    path("ajax_start_search", views.ajax_start_search, name="ajax_start_search"),
    path("ajax_cancel_search", views.ajax_cancel_search, name="ajax_cancel_search"),
    path("ajax_return_new_html_test", views.ajax_return_new_html_test, name="ajax_return_new_html_test")
    # path("get_ajax", views.get_ajax, name="get_ajax")
]

urlpatterns.extend(ajax_patterns)

VChessProject/chess_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class FideTitle(models.Model):
    short_name = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    class Meta:
        unique_together = ('short_name', 'name',)


class ChessUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fide_title = models.ForeignKey(FideTitle, on_delete=models.DO_NOTHING, null=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        ChessUser.objects.create(user=instance)


@receiver(post_save, sender=ChessUser)
def save_user_profile(sender, instance, **kwargs):
    game_types = GameType.objects.all()
    for game_type in game_types:
        r = Rating(chess_user=instance, game_type=game_type, degree_of_confidence=100)
        r.save()


class GameType(models.Model):
    name = models.CharField(max_length=40, primary_key=True)


class Rating(models.Model):
    chess_user = models.ForeignKey(ChessUser, on_delete=models.CASCADE)
    game_type = models.ForeignKey(GameType, on_delete=models.CASCADE)
    rating = models.FloatField(default=1200, null=True)
    last_update = models.DateTimeField(null=True, auto_now=True)
    degree_of_confidence = models.FloatField(default=100, null=False)

    class Meta:
        unique_together = ('chess_user', 'game_type',)


class GameSearchSettings(models.Model):
    game_type = models.ForeignKey(GameType, on_delete=models.CASCADE)
    full_time = models.IntegerField(null=True)
    time_per_move = models.IntegerField(null=True)


class GameResult(models.Model):
    result = models.CharField(max_length=30, primary_key=True)


class Game(models.Model):
    chess_user_white = models.ForeignKey(ChessUser, on_delete=models.DO_NOTHING, related_name="chess_user_white")
    chess_user_black = models.ForeignKey(ChessUser, on_delete=models.DO_NOTHING, related_name="chess_user_black")
    game_result = models.ForeignKey(GameResult, on_delete=models.CASCADE, null=True)
    game_search_settings = models.ForeignKey(GameSearchSettings, on_delete=models.DO_NOTHING)
    is_active = models.BooleanField(default=False)
    white_rating = models.FloatField(null=True)
    black_rating = models.FloatField(null=True)
    start_time = models.DateTimeField(null=True, auto_now_add=True)
    end_time = models.DateTimeField(null=True)
    pgn_file = models.TextField(null=True)


class MoveUCI(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    move_number = models.IntegerField(null=False, blank=False)
    last_update = models.DateTimeField(null=True)
    time_on_clock = models.FloatField(null=True)
    is_white = models.BooleanField(null=False, blank=False)
    uci = models.CharField(max_length=5)

    def __str__(self):
        return f"MoveUCI move_number={self.move_number}, is_white={self.is_white}, uci={self.uci}, " \
               f"clock={self.time_on_clock}, update_time={self.last_update}"

VChessProject/chess_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    username = forms.CharField(required=True, min_length=5, max_length=36,
                               widget=forms.TextInput(attrs={'class': 'input-field', 'placeholder': 'Login'}))
    email = forms.EmailField(required=True,
                             widget=forms.EmailInput(attrs={'class': 'input-field', 'placeholder': 'mail@gmail.com'}))
    password1 = forms.CharField(required=True,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'input-field', 'placeholder': 'Password'}))
    password2 = forms.CharField(required=True,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'input-field', 'placeholder': 'Confirm Password'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'input-field', 'placeholder': 'mail@gmail.com'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


class LoginForm(AuthenticationForm):
    username = forms.CharField(required=True,
                               widget=forms.TextInput(attrs={'class': 'input-field', 'placeholder': 'Login'}))
    password = forms.CharField(required=True,
                               widget=forms.PasswordInput(
                                   attrs={'class': 'input-field', 'placeholder': 'Password'}))

VChessProject/chess_app/views.py
import json
import logging

from pathlib import Path
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, FormView

from .forms import SignUpForm, LoginForm
from .models import Game, Rating, ChessUser
from .tasks import add_player_to_search_queue, delete_player_from_search_queue, start_global_search

logger = logging.getLogger(__name__)


def base_page(request):
    return render(request, Path("chess_app/base/base.html"))


class DefaultLayoutView(TemplateView):
    template_name = "chess_app/default_layout.html"


class SignUpView(FormView):
    form_class = SignUpForm
    template_name = Path("chess_app/sign_up.html")

    def get_success_url(self):
        return reverse('chess_app:log-in')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        user = form.save()
        return super().form_valid(form)


class LogInView(FormView):
    form_class = LoginForm
    template_name = Path("chess_app/log_in.html")

    def get_success_url(self):
        logger.info("You successfully logged in")
        return reverse('chess_app:home_page')

    def form_valid(self, form):
        form.errors['check1'] = ['Check Error']
        user = authenticate(self.request, username=self.request.POST['username'],
                            password=self.request.POST['password'])
        if not user:
            form.errors['sender'] = ["Can't authenticate this user. Please, try again."]
            return render(self.request, Path('chess_app/log_in.html'), {'form': form})
        login(self.request, user)
        return super().form_valid(form)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('chess_app:home_page'))


class BoardView(TemplateView):
    template_name = Path("chess_app/board.html")


def ajax_start_search(request):
    # clear_redis()
    logger.info("Start search")
    start_global_search.delay()
    data = json.loads(tuple(request.GET)[0])
    user = User.objects.get(username=request.user)
    r = add_player_to_search_queue.delay(user.id, data["full_time"], data["additional_time"], 1200)
    return JsonResponse({"How": "Long"})


def ajax_cancel_search(request):
    logger.info("Cancel search")
    user = User.objects.get(username=request.user)
    delete_player_from_search_queue.delay(user.id)
    return JsonResponse({"Cancel": "Search"})


def ajax_get_match_if_found(request):
    logger.info("Getting match")


def ajax_return_new_html_test(request):
    html = render_to_string("chess_app/online_game.html")
    return JsonResponse({"success": True, "new_right_container_html": html})


class OnlineGameView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('chess_app:log-in')
    template_name = "chess_app/online_game.html"

    def get(self, request, game_id):
        self.game = Game.objects.filter(id=game_id).first()
        if not self.game:
            return HttpResponseRedirect(self.login_url)
        return super().get(request, game_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'full_time': self.game.game_search_settings.full_time,
                        'additional_time_per_move': self.game.game_search_settings.time_per_move})
        if self.game:
            game_type = self.game.game_search_settings.game_type.name
            player_white = self.game.chess_user_white
            player_black = self.game.chess_user_black
            rating_white_obj = Rating.objects.filter(chess_user=player_white, game_type=game_type)
            rating_black_obj = Rating.objects.filter(chess_user=player_black, game_type=game_type)
            rating_white = int(rating_white_obj[0].rating) if rating_white_obj else "-"
            rating_black = int(rating_black_obj[0].rating) if rating_black_obj else "-"

            context.update({
                "player_white_name": player_white.user.username,
                "player_black_name": player_black.user.username,
                "player_white_rating": rating_white,
                "player_black_rating": rating_black
            })
        return context


class PlayView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('chess_app:log-in')
    template_name = "chess_app/play_page.html"

    def get(self, request):
        print(f"YO: {request}")
        user = User.objects.get(username=request.user)
        chess_user = ChessUser.objects.get(user=user)
        active_game_list = Game.objects.filter(Q(chess_user_white=chess_user) | Q(chess_user_black=chess_user),
                                               is_active=True)
        if active_game_list:
            active_game = active_game_list[0]
            return HttpResponseRedirect(reverse('chess_app:online_game', kwargs={"game_id": active_game.pk}))
        return super().get(request)

VChessProject/chess_app/templates/chess_app/board.html
{% extends 'chess_app/default_layout.html' %}
{% load static %}

{% block title %}
  Board Analysis
{% endblock %}

{% block stylesheets %}
  {{ block.super }}
  <link type="text/css" href="{% static 'chess_app/css/buttons.css' %}" rel="stylesheet" />
  <link type="text/css" href="{% static 'chess_app/css/chess.css' %}" rel="stylesheet" />
{% endblock %}

{% block right_container %}
  <div class="empty-column-board-left"></div>

  {% include 'chess_app/parts/base_board.html' %}

  <div class="empty-column-board-right"></div>

  <div class="right-menu-column">
    <div class="right-menu-container">
      <div class="right-menu-buttons-container">
        <div class="right-menu-button active" id="notation_button">
          <span><i class="fa-solid fa-location-crosshairs"></i></span>
          <span>Notation</span>
        </div>
        <div class="right-menu-button" id="play_menu_button">
          <span><i class="fa-regular fa-square-plus"></i></span>
          <span>Play</span>
        </div>
      </div>
      <div class="right-menu-content">
        <div class="notation-container" id="notation_container">
          <div class="notation-header">Notation</div>
          <div class="notation-body" id="notation_body"></div>
        </div>
        <div class="play-container" id="play_container">
          <div class="play-body">
            <div class="play-body-row">Time controls</div>

            <div class="play-body-row" id="time_controls_buttons">
              <div class="time-control-button" id="timecontrol_3">3 min</div>
              <div class="time-control-button" id="timecontrol_3_2">3 | 2</div>
              <div class="time-control-button" id="timecontrol_15">15 min</div>
            </div>
            <div class="play-body-row">
              <button class="big-button" id="play_button">Play</button>
              <button class="big-button" id="cancel_button">Cancel search</button>
            </div>
            <div class="play-body-row">
              <button class="big-button" id="test_button">Test</button>
            </div>
            <div class="play-body-row">
              <button class="big-button" id="test_button"><a href="{% url 'chess_app:online_game' game_id='1' %}">Test 2</a></button>
            </div>
          </div>
        </div>
        <div class="players-container" id="players_container"></div>
      </div>

      <div class="right-menu-floor"></div>
    </div>

    <div class="under-menu-buttons-container">
      <div class="move-button" id="first_move_button">
        <i class="fas fa-backward-fast"></i>
      </div>
      <div class="move-button" id="previous_move_button">
        <i class="fas fa-backward"></i>
      </div>
      <div class="move-button" id="next_move_button">
        <i class="fa-solid fa-forward"></i>
      </div>
      <div class="move-button" id="last_main_line_move_button">
        <i class="fa-solid fa-forward-fast"></i>
      </div>
    </div>
  </div>

  {% include 'chess_app/parts/import_pieces_js.html' %}
  <script>
    const url_ajax_start_search = "{% url 'chess_app:ajax_start_search' %}"
    const url_ajax_cancel_search = "{% url 'chess_app:ajax_cancel_search' %}"
    const url_ajax_return_new_html_test = "{% url 'chess_app:ajax_return_new_html_test' %}"
    const basic_url = "{% url 'chess_app:home_page' %}"
  </script>
  <script src="{% static 'chess_app/js/chess_app/right_menu/play.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/pieces.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/pgn.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/right_menu.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/notation.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/chess_pieces_logic.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/chess_game_functions.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/chess_game.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/positions.js' %}" defer></script>
  <script src="{% static 'chess_app/js/board.js' %}" defer></script>
{% endblock %}

VChessProject/chess_app/templates/chess_app/default_layout.html
{% extends 'chess_app/base/base.html' %}
{% load static %}

{% block stylesheets %}
  <link type="text/css" href="{% static 'chess_app/css/menu.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
  <div class="left-menu">
    <div class="top-menu-container">
      <a class="menu-item menu-item-top" href="{% url 'chess_app:play' %}">
        <div class="menu-icon-left">
          <i class="fa-solid fa-magnifying-glass-plus icon-white"></i>
        </div>
        <div class="menu-item-text">Play</div>
      </a>
      <a class="menu-item menu-item-top" href="{% url 'chess_app:board' %}">
        <div class="menu-icon-left">
          <img src="{% static 'chess_app/img/icons/board.png' %}" class="png-icon-board" />
        </div>
        <div class="menu-item-text">Board</div>
      </a>
      <a class="menu-item menu-item-top" href="">
        <div class="menu-icon-left">
          <i class="fa-solid fa-question icon-white" style="font-size: 120%;"></i>
        </div>
        <div class="menu-item-text">About</div>
      </a>
    </div>

    <div class="bottom-menu-container">
      {% if user.is_authenticated %}
        <a class="menu-item menu-item-bottom" href="">
          <div class="menu-icon-left">
            <i class="fa-solid fa-chess-pawn icon-green" style="font-size: 130%;"></i>
          </div>

          <div class="menu-item-text menu-username">{{ user.get_username }}</div>
        </a>
        <a class="menu-item menu-item-bottom" href="{% url 'chess_app:log-out' %}">
          <div class="menu-icon-left">
            <i class="fa-solid fa-plug-circle-xmark icon-red" style="font-size: 120%; padding-left: 4px"></i>
          </div>

          <div class="menu-item-text">Log out</div>
        </a>
      {% else %}
        <a class="menu-item menu-item-bottom" href="{% url 'chess_app:log-in' %}">
          <div class="menu-icon-left">
            <i class="fa-solid fa-right-to-bracket"></i>
          </div>

          <div class="menu-item-text">Log In</div>
        </a>
        <a class="menu-item menu-item-bottom" href="{% url 'chess_app:sign_up' %}">
          <div class="menu-icon-left">
            <i class="fa-solid fa-right-to-bracket"></i>
          </div>

          <div class="menu-item-text">Sign up</div>
        </a>
      {% endif %}
    </div>
  </div>
  <div class="right-container">
    {% block right_container %}

    {% endblock %}
  </div>
{% endblock %}

VChessProject/chess_app/templates/chess_app/log_in.html
{% extends 'chess_app/default_layout.html' %}
{% load static %}

{% block title %}
  <title>Log In</title>
{% endblock %}

{% block stylesheets %}
  {{ block.super }}
  <link type="text/css" href="{% static 'chess_app/css/auth.css' %}" rel="stylesheet" />
  <link type="text/css" href="{% static 'chess_app/css/buttons.css' %}" rel="stylesheet" />
{% endblock %}

{% block right_container %}
  <div class="sign-up-field">
    <h2>Log In</h2>
    <form action="" method="post">
      {% csrf_token %}
      {% if form.errors %}
        {% for k, v in form.errors.items %}
          {% for error in v %}
            <div class="auth-error"><li>{{ error }}</li></div>
          {% endfor %}
        {% endfor %}
      {% endif %}

      {% for field in form %}
        <div class="auth-row">
          {% comment %} <label class="auth-label" for="{{ field.auto_id }}">{{ field.label }}</label> {% endcomment %}
          {{ field }}
        </div>
      {% endfor %}
      <button class="big-button" type="submit">Log In</button>
    </form>
  </div>
{% endblock %}

VChessProject/chess_app/templates/chess_app/online_game.html
{% extends 'chess_app/default_layout.html' %}
{% load static %}

{% block title %}
  Online game
{% endblock %}

{% block stylesheets %}
  {{ block.super }}
  <link type="text/css" href="{% static 'chess_app/css/buttons.css' %}" rel="stylesheet" />
  <link type="text/css" href="{% static 'chess_app/css/chess.css' %}" rel="stylesheet" />
{% endblock %}

{% block right_container %}
  <div class="empty-column-board-left"></div>

  <div class="board-view-column">
    <div class="user-bar-top" id="user_bar_top">
      <div class="board-black-row">
        <div class="user-avatar">
          <img src="{% static 'chess_app/img/icons/no_avatar.png' %}" class="png-icon" />
        </div>
        <div class="user-data">
          <div class="user-name" id="black_username">{{ player_black_name }}</div>
          <div class="user-rating" id="black_rating">({{ player_black_rating }})</div>
        </div>
        <div class="timer-black" id="timer_black">10:00</div>
      </div>
    </div>

    <div class="board-chess-board-row">
      <div class="chess-board" id="chessboard"></div>
      <div class="board-buttons-container">
        <button class="board-button" id="flip_board_button"><i class="fa-solid fa-repeat"></i></button>
      </div>
    </div>
    <div class="user-bar-bottom" id="user_bar_bottom">
      <div class="board-white-row">
        <div class="user-avatar">
          <img src="{% static 'chess_app/img/icons/no_avatar.png' %}" class="png-icon" />
        </div>
        <div class="user-data">
          <div class="user-name" id="white_username">{{ player_white_name }}</div>
          <div class="user-rating" id="white_rating">({{ player_white_rating }})</div>
        </div>
        <div class="timer-white" id="timer_white">10:00</div>
      </div>
    </div>
  </div>

  <div class="empty-column-board-right"></div>

  <div class="right-menu-column">
    <div class="right-menu-container">
      <div class="right-menu-buttons-container">
        <div class="right-menu-button active" id="notation_button">
          <span><i class="fa-solid fa-location-crosshairs"></i></span>
          <span>Notation</span>
        </div>
      </div>
      <div class="right-menu-content">
        <div class="notation-container" id="notation_container">
          <div class="notation-header"></div>
          <div class="notation-body" id="notation_body"></div>
        </div>
        <div class="play-container" id="play_container">
          <div class="play-body">
            <div class="play-body-row">Time controls</div>

            <div class="play-body-row" id="time_controls_buttons">
              <div class="time-control-button" id="timecontrol_3">3 min</div>
              <div class="time-control-button" id="timecontrol_3_2">3 | 2</div>
              <div class="time-control-button" id="timecontrol_15">15 min</div>
            </div>
            <div class="play-body-row">
              <button class="big-button" id="test_button">Test</button>
            </div>
          </div>
        </div>
        <div class="players-container" id="players_container"></div>
      </div>

      <div class="right-menu-floor"></div>
    </div>

    <div class="under-menu-buttons-container">
      <div class="move-button" id="first_move_button">
        <i class="fas fa-backward-fast"></i>
      </div>
      <div class="move-button" id="previous_move_button">
        <i class="fas fa-backward"></i>
      </div>
      <div class="move-button" id="next_move_button">
        <i class="fa-solid fa-forward"></i>
      </div>
      <div class="move-button" id="last_main_line_move_button">
        <i class="fa-solid fa-forward-fast"></i>
      </div>
    </div>
  </div>

  {% include 'chess_app/parts/import_pieces_js.html' %}
  <script>
    const full_time = Number('{{full_time}}')
    const additional_time_per_move = Number('{{additional_time_per_move}}')
  </script>
  <script src="{% static 'chess_app/js/chess_app/online_game_websocket.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/pieces.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/pgn.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/right_menu.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/notation.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/chess_pieces_logic.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/chess_game_functions.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/chess_game.js' %}" defer></script>
  <script src="{% static 'chess_app/js/chess_app/positions.js' %}" defer></script>
  <script src="{% static 'chess_app/js/online_game.js' %}" defer></script>
{% endblock %}

VChessProject/chess_app/templates/chess_app/sign_up.html
{% extends 'chess_app/default_layout.html' %}
{% load static %}

{% block title %}
  <title>Sign up</title>
{% endblock %}

{% block stylesheets %}
  {{ block.super }}
  <link type="text/css" href="{% static 'chess_app/css/auth.css' %}" rel="stylesheet" />
  <link type="text/css" href="{% static 'chess_app/css/buttons.css' %}" rel="stylesheet" />
{% endblock %}

{% block right_container %}
  <div class="sign-up-field">
    <h2>Sign Up</h2>
    <form action="" method="post">
      {% csrf_token %}
      {% if form.errors %}
        {% for k, v in form.errors.items %}
          {% for error in v %}
            <div class="auth-error"><li>{{ error }}</li></div>
          {% endfor %}
        {% endfor %}
      {% endif %}

      {% for field in form %}
        <div class="auth-row">
          {% comment %} <label class="auth-label" for="{{ field.auto_id }}">{{ field.label }}</label> {% endcomment %}
          {{ field }}
        </div>
      {% endfor %}
      <button class="big-button" type="submit">Sign Up</button>
    </form>
  </div>
{% endblock %}